"use client";

import { useCallback, useEffect, useMemo } from "react";
import * as THREE from "three";
import { useThree } from "@react-three/fiber";
import { MeshReflectorMaterial, useTexture } from "@react-three/drei";
import { COUNTER, MARBLE } from "./scene-layout";
import {
  createCounterAlphaTexture,
  createFaceAlphaTexture,
} from "./canvas-textures";

/**
 * The polished marble counter every object in the scene rests on.
 *
 * Three pieces, matching the stone in image.png:
 *
 *   1. A polished top. `MeshReflectorMaterial` renders the scene into a mirror
 *      pass, so the devices' reflections are the real geometry seen in the
 *      stone, not a flipped copy faked underneath them.
 *   2. A bullnose — a half-round front edge. It catches the light edge-on and
 *      is the single strongest cue that this is a slab of stone with
 *      thickness rather than a textured floor.
 *   3. A dark front face under the rim, fading out at its foot, so the counter
 *      reads as furniture running out of the bottom of the hero.
 *
 * ## The stone
 *
 * `counter-marble-4096x2048.webp` is generated by `npm run marble`: cool
 * grey-white ground with a network of charcoal veins, measured off image.png.
 * It is not cut out of image.png — that stone is ~1045 px wide, in steep
 * perspective and full of other objects' reflections; see
 * scripts/build-marble.mjs. The texture tiles seamlessly, and one tile covers
 * `MARBLE.tile` world units, which puts ~455 texels per unit on the counter —
 * more than 2 texels per device pixel even on a DPR-2 drawing buffer at the
 * cluster's 1000 CSS px cap.
 *
 * The earlier stone read brown for three reasons, all removed here: a beige
 * base colour, `metalness` 0.45 (a metallic surface tints its reflections
 * with its own colour) and a strong orange point light filling the slab.
 */
export function Counter() {
  const r = COUNTER.bullnose;
  // The flat top stops where the bullnose starts to curve away; running it
  // on to frontZ would lay a flat lid over the rounded edge.
  const flatFront = COUNTER.frontZ - r;
  const depth = flatFront - COUNTER.backZ;
  const centreZ = (flatFront + COUNTER.backZ) / 2;

  const marble = useTexture(MARBLE.src);
  const maxAnisotropy = useThree((s) => s.gl.capabilities.getMaxAnisotropy());

  /**
   * Each surface gets its own configured copy of the stone.
   *
   * Configuration happens here, on the clone, and not in useTexture's onLoad:
   * that callback runs after the first render, by which point these clones
   * already exist and would have copied the defaults — ClampToEdge wrapping,
   * which smears the texture's last row and column across every repeat and
   * turned the whole counter into horizontal streaks.
   */
  const tiled = useCallback(
    (repeatX: number, repeatY: number) => {
      const t = marble.clone();
      t.colorSpace = THREE.SRGBColorSpace;
      t.wrapS = THREE.RepeatWrapping;
      t.wrapT = THREE.RepeatWrapping;
      // The camera looks across the counter at ~19 degrees; without full
      // anisotropy the stone blurs along the direction it recedes in.
      t.anisotropy = maxAnisotropy;
      t.repeat.set(repeatX, repeatY);
      t.needsUpdate = true;
      return t;
    },
    [marble, maxAnisotropy],
  );

  const topMap = useMemo(
    () => tiled(COUNTER.width / MARBLE.tile[0], depth / MARBLE.tile[1]),
    [tiled, depth],
  );

  // The rim's UVs run around the cylinder (u) and along its length (v), so
  // the slab's texture is laid along v — the veins continue over the edge.
  const rimMap = useMemo(
    () => tiled(0.18, COUNTER.width / MARBLE.tile[0]),
    [tiled],
  );

  const faceMap = useMemo(
    () => tiled(COUNTER.width / MARBLE.tile[0], COUNTER.faceHeight / MARBLE.tile[1]),
    [tiled],
  );

  useEffect(
    () => () => {
      topMap.dispose();
      rimMap.dispose();
      faceMap.dispose();
    },
    [topMap, rimMap, faceMap],
  );

  const alpha = useMemo(() => createCounterAlphaTexture(), []);
  const faceAlpha = useMemo(() => createFaceAlphaTexture(), []);

  return (
    <group>
      {/* Polished top. Laid flat: the plane's local +Y points away from the
          camera, which is the orientation the alpha map is authored for. */}
      <mesh
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, 0, centreZ]}
        receiveShadow
      >
        <planeGeometry args={[COUNTER.width, depth]} />
        <MeshReflectorMaterial
          resolution={1024}
          mixBlur={0.9}
          mixStrength={1.7}
          mixContrast={1.05}
          blur={[160, 60]}
          depthScale={0.6}
          minDepthThreshold={0.4}
          maxDepthThreshold={1.4}
          mirror={0.5}
          color="#b9babe"
          map={topMap}
          roughness={0.28}
          metalness={0}
          envMapIntensity={0.9}
          alphaMap={alpha}
          transparent
          depthWrite={false}
        />
      </mesh>

      {/* Bullnose: a half-round edge whose top is flush with the surface.
          Rotated so the cylinder runs along x; theta -90..90 degrees is the
          half that faces the camera. No alpha map: the cylinder's UVs run
          around and along it, not across the slab, and the canvas edge mask
          already dissolves its ends. */}
      <mesh
        position={[0, -r, flatFront]}
        rotation={[0, 0, Math.PI / 2]}
      >
        <cylinderGeometry args={[r, r, COUNTER.width, 48, 1, true, -Math.PI / 2, Math.PI]} />
        <meshPhysicalMaterial
          map={rimMap}
          color="#a9aaae"
          roughness={0.3}
          clearcoat={1}
          clearcoatRoughness={0.18}
          envMapIntensity={0.8}
          side={THREE.DoubleSide}
        />
      </mesh>

      {/* Front face under the rim, in shadow, dissolving toward the bottom. */}
      <mesh position={[0, -2 * r - COUNTER.faceHeight / 2, flatFront]}>
        <planeGeometry args={[COUNTER.width, COUNTER.faceHeight]} />
        <meshStandardMaterial
          map={faceMap}
          color="#3a3b40"
          roughness={0.4}
          alphaMap={faceAlpha}
          transparent
          depthWrite={false}
        />
      </mesh>
    </group>
  );
}
