/**
 * Measured geometry for the 3D hero product scene.
 *
 * ## Unit system
 *
 * 1 world unit = 100 px of `image.png` (1045x803), the approved composite for
 * this cluster. The counter's top surface is the y=0 plane, so every object's
 * "sits on the counter" condition is literally `bottom === 0`. The scene box
 * measured off image.png is x 35..1015 px, so world x is
 * `(imagePx - 35) / 100 - SCENE_CENTRE_X`, which centres the composition on
 * the origin.
 *
 * ## What is measured and what is derived
 *
 * Body widths, x positions and Y rotations are measured from image.png with a
 * 25px grid overlaid. Screen *heights* are never measured — they are derived
 * from the real texture aspect ratio, because the screenshots are used at their
 * true proportions and are never stretched or cropped (docs/IMAGE_PIPELINE.md).
 * Where our asset is shaped differently from the reference hardware, the object
 * matches the reference's width and contact point and its height falls where
 * the asset puts it. See docs/ASSET_MANIFEST.md.
 *
 * ## Rotation sign convention
 *
 * three.js `rotation.y` is counter-clockwise seen from above, so a *positive*
 * value turns an object's right edge away from the camera — the same sense as
 * CSS `rotateY`. Objects left of centre therefore take positive values (they
 * face inward, to the right) and objects right of centre take negative ones.
 * The magnitudes come from comparing each device's left and right edge heights
 * in image.png: the taller edge is the nearer one.
 *
 * `rotation.x` is negative for a natural backward lean (top edge away).
 */

const DEG = Math.PI / 180;

/** Centre of the measured scene box, in world units before centring. */
const SCENE_CENTRE_X = 4.9;

/** image.png x pixel -> centred world x, valid in the z = 0 plane. */
const x = (imagePx: number) => imagePx / 100 - 0.35 - SCENE_CENTRE_X;

/**
 * Perspective correction for an object standing at depth z.
 *
 * "1 unit = 100 px" only holds in the z = 0 plane, ~22.6 units from the
 * camera. An object placed further back projects smaller, so a width measured
 * on the reference has to be scaled up by its distance ratio to land at the
 * measured size — and likewise its x offset from the view centre. Without
 * this the rear monitor, at z = -2.4, rendered ~10% narrower than measured.
 */
const CAMERA_DISTANCE = 22.6;
const depth = (z: number) => (CAMERA_DISTANCE - z) / CAMERA_DISTANCE;
/** Measured width at depth z. */
const w = (units: number, z: number) => units * depth(z);
/** Measured x at depth z. */
const xz = (imagePx: number, z: number) => x(imagePx) * depth(z);

/** Texture aspect ratios, from the real published texture dimensions. */
export const TEXTURE_ASPECT = {
  dashboard: 1442 / 1091,
  kitchen: 1672 / 941,
  pos: 1448 / 1086,
  mobile: 941 / 1672,
} as const;

export const TEXTURES = {
  dashboard: "/textures/nexa-dashboard.webp",
  kitchen: "/textures/nexa-kitchen.webp",
  pos: "/textures/nexa-pos.webp",
  mobile: "/textures/nexa-mobile.webp",
} as const;

/**
 * Counter stone, generated by `npm run marble` (scripts/build-marble.mjs).
 * One seamless 4096x2048 tile covers `tile` world units: ~455 texels per unit.
 * The tile is smaller than the visible counter on purpose — at 16 units the
 * whole visible slab showed only two or three veins, far sparser than the
 * stone in image.png.
 */
export const MARBLE = {
  src: "/textures/counter-marble-4096x2048.webp",
  tile: [9, 4.5] as [number, number],
} as const;

export type DeviceSpec = {
  /** Outer shell width in world units. */
  bodyWidth: number;
  /** Bezel thickness on the left and right of the screen. */
  side: number;
  /** Bezel above the screen. */
  top: number;
  /** Bezel below the screen — the chin. */
  chin: number;
  /** Shell thickness front to back. */
  depth: number;
  /** Texture aspect (w/h); the screen height is derived from it. */
  aspect: number;
  /**
   * Where the object touches the counter. Y is always 0 — that is the whole
   * point of putting the counter's surface on the y = 0 plane, and it means
   * "this device stands on the counter" is structural rather than a number
   * each device has to get right on its own.
   */
  position: [number, number, number];
  /**
   * How far the stand raises the shell above the counter. The shell is placed
   * at `lift + bodyHeight/2`, and the stand geometry fills 0..lift underneath
   * it. Zero for objects that sit directly on the stone, like the phone.
   */
  lift: number;
  rotation: [number, number, number];
  /**
   * Corner radius of the visible screen, as a fraction of the screen's
   * shorter side. Real panels are never square-cornered; a hard 90-degree
   * screenshot corner is one of the quickest tells of a pasted-on image.
   */
  screenRadius?: number;
  /**
   * Black glass border between the shell and the live pixels. On the monitor
   * this is what separates the silver frame from the UI, as in image.png.
   */
  glassBorder?: number;
};

/** Screen width implied by a spec. */
export const screenWidth = (d: DeviceSpec) => d.bodyWidth - 2 * d.side;
/** Screen height implied by a spec and its texture's true aspect. */
export const screenHeight = (d: DeviceSpec) => screenWidth(d) / d.aspect;
/** Total shell height implied by a spec. */
export const bodyHeight = (d: DeviceSpec) =>
  d.top + screenHeight(d) + d.chin;

/**
 * Rear monitor — the neXa dashboard. Dominant object, furthest back.
 * image.png body 262..790 px wide, so 5.28 units.
 */
export const MONITOR: DeviceSpec = {
  bodyWidth: w(5.28, -2.4),
  side: 0.15,
  top: 0.15,
  chin: 0.22,
  depth: 0.22,
  aspect: TEXTURE_ASPECT.dashboard,
  position: [xz(526, -2.4), 0, -2.4],
  // base 0.09 + neck 1.49. Puts the monitor top at y 193 of the reference;
  // its base stays hidden behind the POS, which opens up the dashboard.
  lift: 1.58,
  rotation: [-4 * DEG, -7 * DEG, 0],
  screenRadius: 0.012,
  glassBorder: 0.07,
};

/** Monitor stand, in units. */
export const MONITOR_STAND = {
  neck: { width: 0.42, height: 1.49, depth: 0.22 },
  base: { radius: 0.78, height: 0.09, squash: 0.62 },
} as const;

/**
 * POS terminal — front and centre on its branded wedge base, standing over the
 * monitor's lower half exactly as image.png stages it.
 * image.png body 289..619 px, base 325..566 x 592..649.
 */
export const POS: DeviceSpec = {
  bodyWidth: w(3.3, -0.5),
  side: 0.11,
  top: 0.11,
  chin: 0.22,
  depth: 0.18,
  aspect: TEXTURE_ASPECT.pos,
  position: [xz(454, -0.5), 0, -0.5],
  // The wedge base.
  lift: 0.57,
  rotation: [-3 * DEG, 6 * DEG, 0],
  screenRadius: 0.025,
};

/** The wedge the POS stands on. Measured at 73% of the terminal's width. */
export const POS_BASE = {
  topWidth: 2.2,
  bottomWidth: 2.41,
  height: 0.57,
  depth: 1.05,
} as const;

/**
 * Kitchen display — a large tablet, right of frame, angled inward. In
 * image.png it is a slim black slate with even thin bezels, leaning back on a
 * rear kickstand with its bottom edge almost on the stone — not a monitor on a
 * neck. The strongest turn in the scene: 300px right edge against 261 left.
 */
export const KITCHEN: DeviceSpec = {
  bodyWidth: w(3.9, -0.9),
  side: 0.12,
  top: 0.12,
  // Slightly deeper bottom bezel, which carries the small maker mark.
  chin: 0.17,
  depth: 0.09,
  aspect: TEXTURE_ASPECT.kitchen,
  position: [xz(817, -0.9), 0, -0.9],
  // The rubber front lip it rests on.
  lift: 0.07,
  rotation: [-12 * DEG, -11 * DEG, 0],
  screenRadius: 0.03,
};

/** Rear kickstand and front lip the kitchen tablet rests on. */
export const KITCHEN_STAND = {
  lip: { width: 3.5, height: 0.07, depth: 0.14 },
  /** Folding plate behind the slate, hinged near its top third. */
  plate: { width: 2.2, height: 1.6, depth: 0.05 },
} as const;

/**
 * Phone — front left, paired with the QR stand. Black glass front with thin
 * even bezels, a titanium side frame and a Dynamic-Island-style cut-out, as
 * the iPhone in image.png. The screen keeps our capture's true 0.56 ratio, so
 * the phone is stockier than the reference's 0.46 — see ASSET_MANIFEST.
 */
export const PHONE: DeviceSpec = {
  bodyWidth: w(1.33, -2.2),
  side: 0.05,
  top: 0.05,
  chin: 0.05,
  depth: 0.1,
  aspect: TEXTURE_ASPECT.mobile,
  // z set by the reference contact line: in a 1672x941 overlay the phone's
  // foot lands on its y 745 at z = -2.2 (still in front of the monitor).
  position: [xz(220, -2.2), 0, -2.2],
  // Stands directly on the stone.
  lift: 0,
  rotation: [-4 * DEG, 5 * DEG, 0],
  screenRadius: 0.13,
};

/** QR table stand — frontmost object, beside the phone. */
export const QR_STAND = {
  width: w(1.02, -2.0),
  height: w(1.87, -2.0),
  depth: 0.05,
  // Foot on the reference's y 765 in overlay: z = -2.0.
  position: [xz(95, -2.0), 0, -2.0] as [number, number, number],
  rotation: [-7 * DEG, 9 * DEG, 0] as [number, number, number],
  /** The acrylic foot the card stands in; the card starts at its top. */
  lift: 0.1,
  foot: { width: 0.78, height: 0.1, depth: 0.42 },
} as const;

/**
 * The counter. A finite slab, not an infinite ground plane: with the camera
 * pitched 11 degrees down the horizon of an infinite plane would land near the
 * top of the frame and the stone would fill the whole canvas. The slab's far
 * edge is faded out with an alpha map instead, so the counter dissolves into
 * the photographic background rather than ending on a line.
 */
export const COUNTER = {
  width: 44,
  /**
   * The front edge of the stone. image.png shows the polished top ending in a
   * rounded bullnose across the bottom of the frame (rim y 725..785), with a
   * clear band of counter in front of the QR stand and phone. At z = 2.4 the
   * edge projects just below the measured scene box; the canvas covers the
   * whole hero, so the rim and the dark front face below it are drawn.
   */
  frontZ: 2.4,
  /**
   * The back edge. The reference shows a bar-depth counter: its far edge is a
   * horizontal line at about y 740 of 1672x941, just behind the monitor (at
   * z = -2.4), with the lit bar beyond it. -3.0 projects there, clearing
   * the monitor foot (which reaches back to z -2.88). An earlier
   * -17 ran the stone up to the benefit icons once the canvas went full-bleed.
   */
  backZ: -3.0,
  /** Bullnose radius: a full half-round edge, ~0.56 units tall as measured. */
  bullnose: 0.28,
  /** Height of the dark front face under the rim, faded out at its foot. */
  faceHeight: 3.2,
} as const;

/**
 * Camera. Slightly elevated, long lens.
 *
 * fov 17.5 at ~23 units is roughly a 135mm equivalent — the lens product
 * photography actually uses, and the reason the scene can be genuinely 3D and
 * still resemble a flat composite.
 *
 * A first pass used fov 30 at 12.6 units. The framing was right but the
 * perspective divergence was not: the POS sits two units in front of the
 * monitor, and at that focal length it projected 21% larger relative to it
 * than image.png shows, burying more than half the dashboard. Pulling the
 * camera back and narrowing the fov keeps the same field while compressing
 * near-to-far size differences, so the measured proportions survive without
 * flattening the staging.
 *
 * The pitch is 11.2 degrees down (dy 4.3 over dz 22.6), which is what puts a
 * band of counter in front of the devices as in the reference. The fov and
 * aspect describe the measured device box only; the full-bleed canvas around
 * it is rendered with a view offset (see CameraRig in product-scene.tsx).
 */
export const CAMERA = {
  position: [0.35, 7.24, 22.6] as [number, number, number],
  target: [0.1, 2.94, 0] as [number, number, number],
  fov: 17.5,
} as const;
